#!/usr/bin/env python
'''
fips build system main script
'''
VERSION = '0.0.1'

import sys
import os
from mod import log
from mod.verbs import diag,list
try :
    import yaml 
except ImportError:
    log.error("could not import 'yaml', run 'pip --user install PyYAML' to install")

verbs = {
    'diag': diag,
    'list': list
}

fips_path = os.path.dirname(os.path.abspath(__file__))
proj_path = fips_path

#-------------------------------------------------------------------------------
def show_help(args) :
    """show help text"""
    log.info("fips: the high-level, multi-platform build system wrapper\n"
             "v{}\n"
             "https://www.github.com/floooh/fips\n".format(VERSION))
    for verb in [list, diag] :
        verb.help()
        log.info(' ')

#===============================================================================
if len(sys.argv) <= 1:
    print("run 'fips help' for more info")
else :
    verb = sys.argv[1]
    verb_args = sys.argv[2:]
    if verb == 'help' or verb == '--help' or verb == '-help' :
        show_help(verb_args)
    elif verb == '--version' :
        log.info(VERSION)
    elif verb in verbs :
        verbs[verb].run(fips_path, proj_path, verb_args)
    else :
        log.error("unknown verb '{}'".format(verb))






