#!/usr/bin/env python
"""fips main entry"""
import os
import sys
proj_path = os.path.dirname(os.path.abspath(__file__))
fips_path = os.path.dirname(proj_path) + '/fips'
sys.path.insert(0,fips_path)
try :
    from mod import fips
except ImportError :
    print("\n\033[91m[ERROR]\033[0m fips build system not found, get it with:\n"
          "  > cd ..\n"
          "  > git clone git@github.com:floooh/fips.git fips")
    sys.exit(10)
fips.run(fips_path, proj_path, sys.argv)
